### ISSUE TITLE
Whitelist Users Request

### ISSUE THREAD

**Issue by alazymeme** [MrEliasen/twitch-bot-list#12]
# What is this issue about?

- [ ] Add an account
- [x] Remove an account

# Confirm you checked the accounts are not already on the lists?

- [x] Yes I checked

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

- amazeful
- naughtygirlnextdoor
- overrustlelogs

### Reason for adding or removing from list:

- Amazeful is not a bot: https://i.nuuls.com/XHRo0.png
- naughtygirlnextdoor was last active 141 days ago, but definitely isn't a bot: https://i.nuuls.com/uxIOq.png
- overrustlelogs - Given the newest twitch feature in relation to banned users, overrustlelogs should definitely be whitelisted

**Comment by MrEliasen** [comment]
**naughtygirlnextdoor** must have changed name or had their account closed.
**amazeful** might not be a bot, but if their have their presence in a lot of channels they will remain on this list.

Appreciate the heads up on overrustlelogs! That one should not have been on the list. It is now whitelisted.

**Comment by alazymeme** [comment]
@MrEliasen Amazeful has a presence in a lot of channels due to the chat program "chatterino". Allows you to open multiple tabs on one connection. Lots of people use chatterino and have a lot of tabs open: https://github.com/Chatterino/chatterino2

**Comment by MrEliasen** [comment]
Ahh I see! Appreciate the additional details.
Whitelisting the account now.

Cheers
