### ISSUE TITLE
amazefulbot

### ISSUE THREAD

**Issue by alazymeme** [MrEliasen/twitch-bot-list#16]
@MrEliasen Not sure what you want to do with `amazefulbot` - it's amazeful, but they've moved the bot functions to a bot account. Not sure which list to put it on

**Comment by MrEliasen** [comment]
What does that mean? Is amazefulbot is the one which joins channels or amazeful is the one joining channels? I guess we put amazefulbot on the same list as amazeful is needed I suppose?

**Comment by alazymeme** [comment]
So amazeful was being used as the bot account previously, now that has moved to amazefulbot (not sure if amazeful is still being used as a bot account)

**Comment by MrEliasen** [comment]
Alright, lets keep amazeful on the list and put amazefulbot with it, seems reasonable I would say.

**Comment by MrEliasen** [comment]
resolved in 4bc2c4a9b0b9835c96101d7594e35e3d954ef122
