### ISSUE TITLE
Depreciation and shutdown of the website

### ISSUE THREAD

**Issue by MrEliasen** [MrEliasen/twitch-bot-list#18]
I have been thinking about shutting down the website since with the new and more efficient ban system, it's become fairly obsolete in my opinion. I will make a decision by the end of the year at latest.

If you have any feedback, reasons to shut it down or keep it up, please do comment or vote with an emote.

👍🏻  = Keep it up and running
👎🏻  = Shut it down, call it a day.

Thanks!

**Comment by Ravarion** [comment]
Hey MrEliasen, I'm currently fetching your json list of bots for my own bot to ban them on sight.  I first attempted to gather bot data from twitchinsights.net but it doesn't really seem feasible with how that website is set up.  Your json has made it simple to grab an iterable list at the beginning of my stream.

Wanted to let you know that it's useful to me.  Thanks!

**Comment by MrEliasen** [comment]
The list if not 100% up to date, since accounts can change names and also some of them no longer exists or have been banned by Twitch, I scrape the latest list from twitch insights this weekend and update the json.

It looks like people generally wants the tool to remain up, so It shall. However it is being very slow at banning due to Twitch API rate limits. I tried to sort this out but for whatever reason it simply didn't want to go beyond the lowest rate limit imposed by Twitch.

**Comment by Ravarion** [comment]
Hey MrEliasen, I just posted a video tutorial that utilizes your work.
https://youtu.be/3uuieCAzh-Q
Thanks again for putting this resource together, it's been really useful!

**Comment by MrEliasen** [comment]
Pleasure, but really the credit goes to Twitch Insights :).

Also it might be useful to you; I just update the repo with more details and a `parse.js` file which is a very simple script which shows how I update the list.

However please do not hammer Twitch Insights API if you decide to use it, instead pull just now and again and cache the list is my recommendation (or use this repository).

All the best
