### ISSUE TITLE
Remove yosefsa7 and yosef_the_spammer

### ISSUE THREAD

**Issue by ALazyMeme** [MrEliasen/twitch-bot-list#21]
# What is this issue about?

- [x] Remove an account

# Confirm you checked the accounts are not already on the lists?

- [x] Yes I checked

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

- yosefsa7
- yosef_the_spammer

### Reason for adding or removing from list:

Someone I know that owns both those accounts. They belong to a person.

**Comment by MrEliasen** [comment]
@ALazyMeme When I look them up on Twitch, they do not appear to be found. Chances are the names have changed. Happy to remove on those grounds alone.

**Comment by ALazyMeme** [comment]
> @ALazyMeme When I look them up on Twitch, they do not appear to be found. Chances are the names have changed. Happy to remove on those grounds alone.

Both accounts were banned indefinitely

**Comment by MrEliasen** [comment]
RIP in peace
