### ISSUE TITLE
Remove Dragonzzin

### ISSUE THREAD

**Issue by ALazyMeme** [MrEliasen/twitch-bot-list#23]
### What is this issue about?

- [ ] Add an account
- [x] Remove an account

### Confirm you checked the accounts are not already on the lists?

- [x] Yes I checked

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

Dragonzzin

### Reason for adding or removing from list:

They asked me, I don't think bots would whisper people and ask them to be removed from a bot list

Please provide as many details and "evidence" as possible:

![image](https://user-images.githubusercontent.com/12804673/132927347-17255dbd-2283-40c7-b275-829fdfeb6bd0.png)

**Comment by MrEliasen** [comment]
I have removed the bot list entirely, as the website now utilises the online bots list directly from Twitch Insights

**Comment by ALazyMeme** [comment]
> I have removed the bot list entirely, as the website now utilises the online bots list directly from Twitch Insights

Twitch Insights was proved by a couple of people within the community that I'm in as being terrible. It's not difficult to get yourself on that bot list and there are a genuine fuck ton of false positives.
