### ISSUE TITLE
2 more bots to add !

### ISSUE THREAD

**Issue by baronfortesque** [MrEliasen/twitch-bot-list#3]
# What is this issue about?

- [X] Add an account
- [ ] Remove an account 

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

angeloflight
energyzbot

### Reason for adding or removing from list:

Please provide as many details and "evidence" as possible.

All  have things on their twitch panels saying either that they lurk, watch  other streams and will host you in raffles. They also never said a word  in my stream and they always are there!
--

**Comment by baronfortesque** [comment]
I said 3, but you already had skinnyseahorse in there. I had to check my userlists in streamlabs chatbot and look them up :P

**Comment by MrEliasen** [comment]
I can confirm both does appear to be bots as they even state so in their panels. They have been added to the list.

Also appreciate checking for duplicates first! :)

**Comment by baronfortesque** [comment]
You're welcome. Glad to be able to help fight this :)
