### ISSUE TITLE
Some bots to add

### ISSUE THREAD

**Issue by Vantazzy** [MrEliasen/twitch-bot-list#4]
# What is this issue about?

- [ ] Add an account
- [ ] Remove an account 

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

- n3td3v
- lurxx
- electricalskateboard
- slocool
- electricallongboard
- v_and_k
- decafsmurf
- bananennanen
- teyyd
- virgoproz
- teyd__
- host_giveaway
- angeloflight
- s1faka
- energyzbot
- hostmeraffle
- freddyybot

### Reason for adding or removing from list:

These names are mostly all the time in my chat, no talking, nothing. I even made a lurker rewarding system, where I send a message to them, but no response and some have whispers blocked. I got more names, but those are actual streamers but just planted something there, I want to ask them personally to remove them first before I add those names too.

**Comment by MrEliasen** [comment]
Hi there, thank you for contributing!
I have just updated the list with all the bots currently online - as per https://twitchinsights.net/bots
