### ISSUE TITLE
PokemonCommunityGame

### ISSUE THREAD

**Issue by pallen0304** [MrEliasen/twitch-bot-list#46]
# What is this issue about?

- [x] Add an account to whitelist
- [ ] Add an account to greylist
- [ ] Remove an account from whitelist
- [ ] Remove an account from greylist

IMPORTANT:
This repository no longer serves a list of bots. Instead it now only acts as a sort of personal white/greylist. The list of bots/accounts are loaded directly from [Twitch Insights](https://twitchinsights.net/bots), I do NOT control what is on that list.

# Confirm you checked the accounts are not already on the lists?

- [x] Yes I checked

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

pokemoncommunitygame

### Reason for adding or removing from list:
Please provide as many details and "evidence" as possible.

This account is an invite-only bot that works with the Twitch Extension "PokemonCommunityGame". I believe it should be treated similarly to ButtsBot, as any other invite-only bot, and whitelisted so channels don't accidentally ban this chat bot.

Extension: https://dashboard.twitch.tv/extensions/pm0qkv9g4h87t5y6lg329oam8j7ze9-0.8.6
Channel with more info: https://www.twitch.tv/pokemoncommunitygame
*This is not my own Twitch Account, but I want to be able to use this tool without accidentally banning my favorite chat bots!

**Comment by MrEliasen** [comment]
Done 👍🏻
