### ISSUE TITLE
Add sery_bot to whitelist

### ISSUE THREAD

**Issue by serycodes** [MrEliasen/twitch-bot-list#47]
# What is this issue about?

- [x] Add an account to whitelist
- [ ] Add an account to greylist
- [ ] Remove an account from whitelist
- [ ] Remove an account from greylist

IMPORTANT:
This repository no longer serves a list of bots. Instead it now only acts as a sort of personal white/greylist. The list of bots/accounts are loaded directly from [Twitch Insights](https://twitchinsights.net/bots), I do NOT control what is on that list.

# Confirm you checked the accounts are not already on the lists?

- [x] Yes I checked

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

- Sery_Bot

### Reason for adding or removing from list:

Please provide as many details and "evidence" as possible.

Sery_Bot is a verified bot providing moderation and stream tools as an opt-in bot.
https://twitch.tv/sery_bot
https://serycodes.carrd.co

**Comment by MrEliasen** [comment]
Added in https://github.com/MrEliasen/twitch-bot-list/commit/37227f0753c911b716cb677f0b6c98211a101ef3
