### ISSUE TITLE
Add 7tvApp to whitelist 

### ISSUE THREAD

**Issue by TroyKomodo** [MrEliasen/twitch-bot-list#48]
# What is this issue about?

- Add an account to whitelist

IMPORTANT:
This repository no longer serves a list of bots. Instead it now only acts as a sort of personal white/greylist. The list of bots/accounts are loaded directly from [Twitch Insights](https://twitchinsights.net/bots), I do NOT control what is on that list.

# Confirm you checked the accounts are not already on the lists?

- [ ] Yes I checked

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

7tvapp

---
Hi, my name is Troy and I am speaking officially on behalf of 7tv.app. Please can you add us to the whitelist <3 it would be greatly appreciated thank you <3

**Comment by MrEliasen** [comment]
Done in https://github.com/MrEliasen/twitch-bot-list/commit/00387918a85ae0cff4864af142ce93596b99fcfe
