### ISSUE TITLE
Bot not added to ban list - freddyybot

### ISSUE THREAD

**Issue by dylmye** [MrEliasen/twitch-bot-list#5]
# What is this issue about?

- [ ] Add an account
- [x] Remove an account

# Confirm you checked the accounts are not already on the lists?

- [x] Yes I checked

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:
freddyybot - mentioned in #4

**Comment by MrEliasen** [comment]
Just to confirm, you are asking me to add the bot to the list right? (I think you checked the wrong box that is all)

**Comment by dylmye** [comment]
yes, my bad!

**Comment by MrEliasen** [comment]
Ah just wanted to make sure :)!
