### ISSUE TITLE
Remove Bot

### ISSUE THREAD

**Issue by Felanbird** [MrEliasen/twitch-bot-list#6]
# What is this issue about?

- [X] Remove an account

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:
- felanbird

### Reason for adding or removing from list:
- I'm not a bot

Please provide as many details and "evidence" as possible.

- I'm myself
- The twitch god of war regex has put an almost stop to gifted sub farming
- I'm in a lot of channels for the purpose of personal logging,

**Comment by MrEliasen** [comment]
Could you point me to any official news/posts about why its harder to farm gifted subs?
Looking at Twitch Insights and their data in mind, I am happy to remove you from the list!

Thank you for letting me know!

**Comment by Felanbird** [comment]
@MrEliasen I cant prove it with any news, I can only go by word of mouth that everyone I know who sub farmed went from easily having 99+ gifts to barely being able to surpass 10. Some of which went multiple months without receiving a random gifted sub. 🤔
