### ISSUE TITLE
My own personal account is listed as a bot

### ISSUE THREAD

**Issue by RAnders00** [MrEliasen/twitch-bot-list#7]
# What is this issue about?

- [ ] Add an account
- [x] Remove an account

# Confirm you checked the accounts are not already on the lists?

- [x] Yes I checked

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

- randers

### Reason for adding or removing from list:

Please provide as many details and "evidence" as possible.

randers is my own twitch account. As evidence, I have created a panel on my own twitch page that links to this issue:  https://www.twitch.tv/randers

**Comment by MrEliasen** [comment]
Noted and removed based on information provided and with Twitch Insights. Thank you for letting me know!
