### ISSUE TITLE
Remove Commonly Used Chatbots from the list

### ISSUE THREAD

**Issue by alazymeme** [MrEliasen/twitch-bot-list#9]
# What is this issue about?

- [ ] Add an account
- [x] Remove an account

# Confirm you checked the accounts are not already on the lists?

- [x] Yes I checked

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

- StreamElements
- Streamlabs
- Nightbot
- Dinu
- Logviewer
- Moobot

### Reason for adding or removing from list:

StreamElements is a standard chatbot that people use
Streamlabs         ^^^^^^^^^^^^^^^^^^^^^^^^
Nightbot            ^^^^^^^^^^^^^^^^^^^^^^^^
Moobot             ^^^^^^^^^^^^^^^^^^^^^^^^
Dinu is ex twitch staff and would often lurk in channels. I would in no way call him a bot. In fact, he talks in channels: https://i.nuuls.com/ZYNjY.png
Logviewer is Cbenni's bot that is only added to your channel when logging - This should be an optional ban

**Comment by MrEliasen** [comment]
Sorted! That is a mistake my end, I updated the list late at night and forgot to cross reference with the whitelist! Thank you for catching that <3

**Comment by alazymeme** [comment]
@MrEliasen What about logviewer and overrustlelogs? I feel like they shouldn't be on the list either...

**Comment by RAnders00** [comment]
Logviewer is a whitelist bot that only joins a channel when the broadcaster wants logviewer to be there so I don't understand why it was placed on the greylist

**Comment by MrEliasen** [comment]
I have greylisted them for now while the debate is on.
Ideally I would see any bot who is not a person or who is just farming gift subs to be on the list. does overrustlelogs and logviewer have issues with their service if they are banned? If so, I leave them on the greylist.

Let me know!

**Comment by alazymeme** [comment]
No there are no issues, but both bots are optional to add and aren't a pest. I don't believe they should be on the banned list - if people want them removed, they can just ask for them to be removed...

**Comment by MrEliasen** [comment]
But its not really a matter of which are a pest and which are not, more so to avoid bots getting random sub gifts. I can understand bots which have functionality in the chat, like commands etc (nightbot, etc ), but bots which just linger in the background can easily be banned and see log the chat like Logviewer and overrustledlogs.

Do correct me if I am wrong, but I dont see any downside to banning these?

**Comment by alazymeme** [comment]
As per my previous comment; there is no downside.

**Comment by RAnders00** [comment]
logviewer can log moderator actions like timeouts and bans which only works when it's modded, banning logviewer would unmod it and degrade its functionality

**Comment by MrEliasen** [comment]
Good to know with logviewer, I will move it to the whitelist with that in mind.

Thank you very much guys for the info!
